name: IRChouine tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Your beautiful code vs some scary tester
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run tests
        env:
          TERM: xterm-256color
        run: make docker-test
